version: '3'
services:
  etcd:
    hostname: etcd
    image: public.ecr.aws/vanus/etcd:v3.5.7
    pull_policy: missing
    container_name: etcd
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    privileged: true
    volumes:
      - "/etcd/data:/opt/bitnami/etcd/data"
    environment:
      - "ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
      - "ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380"
      - "ETCD_INITIAL_ADVERTISE_PEER_URLS=http://0.0.0.0:2380"
      - "ALLOW_NONE_AUTHENTICATION=yes"
      - "ETCD_INITIAL_CLUSTER=node1=http://0.0.0.0:2380"
      - "ETCD_NAME=node1"
      - "ETCD_DATA_DIR=/opt/bitnami/etcd/data"
      - "ETCD_QUOTA_BACKEND_BYTES=8589934592"
      - "ETCD_AUTO_COMPACTION_MODE=periodic"
      - "ETCD_AUTO_COMPACTION_RETENTION=60m"
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - vanus
  root-controller:
    image: public.ecr.aws/vanus/root-controller:v0.9.0
    pull_policy: missing
    container_name: root-controller
    volumes:
      - ./config/root-controller.yaml:/vanus/config/root.yaml
    environment:
      - "VANUS_LOG_LEVEL=INFO"
    expose:
      - 2021
      - 2110
    networks:
      - vanus
  controller:
    image: public.ecr.aws/vanus/controller:v0.9.0
    pull_policy: missing
    container_name: controller
    volumes:
      - ./config/controller.yaml:/vanus/config/controller.yaml
    environment:
      - "VANUS_LOG_LEVEL=INFO"
    expose:
      - 2048
      - 2112
    networks:
      - vanus
    depends_on:
      - root-controller
  store:
    container_name: store
    image: public.ecr.aws/vanus/store:v0.9.0
    pull_policy: missing
    volumes:
      - ./config/store.yaml:/vanus/config/store.yaml
    environment:
      - "VANUS_LOG_LEVEL=INFO"
      - "VOLUME_ID=1"
    expose:
      - 11811
      - 2114
    networks:
      - vanus
    depends_on:
      - controller
  timer:
    container_name: timer
    image: public.ecr.aws/vanus/timer:v0.9.0
    pull_policy: missing
    volumes:
      - ./config/timer.yaml:/vanus/config/timer.yaml
    environment:
      - "VANUS_LOG_LEVEL=INFO"
    expose:
      - 2115
    networks:
      - vanus
    depends_on:
      - controller
      - store
  trigger:
    container_name: trigger
    image: public.ecr.aws/vanus/trigger:v0.9.0
    pull_policy: missing
    volumes:
      - ./config/trigger.yaml:/vanus/config/trigger.yaml
    environment:
      - "VANUS_LOG_LEVEL=INFO"
    expose:
      - 2116
    networks:
      - vanus
    depends_on:
      - controller
  gateway:
    container_name: gateway
    image: public.ecr.aws/vanus/gateway:v0.9.0
    pull_policy: missing
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./config/gateway.yaml:/vanus/config/gateway.yaml
    environment:
      - "VANUS_LOG_LEVEL=INFO"
    expose:
      - 2113
    networks:
      - vanus
    depends_on:
      - controller
      - store
      - trigger
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    expose:
      - 9090
    ports:
      - "9090:9090"
    command:
      - --storage.tsdb.retention=6h
      - --storage.tsdb.path=/prometheus
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - vanus
  grafana:
    container_name: grafana
    image: public.ecr.aws/vanus/observability/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/datasource.yaml:/home/grafana/provisioning/datasources/prometheus.yaml
    networks:
      - vanus
networks:
  vanus:
    driver: bridge
